config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:"items#index"
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  #タイトルは必須項目かつ、20文字上限
  validates :title, presence: true, length: {maximum: 20}
  validates :start, presence: true
  validates :end, presence: true
  validates :memo, length: {maximum: 500}

  validate :start_end_over #カスタムはvalidate

  private
  #開始日が終了日よりも後にならないように
  def start_end_over
    if self.start.present? && self.end.present? && self.start >= self.end #startとendはカラム名としてアクセスするため、self.startとself.endを使用し、dateのためpresent
      errors.add(:base, "終了日は、開始日以降の日付としてください") #:startだと、Start開始日は終了日時より前で選択してくださいと表示されてしまうため、全体的なエラーメッセージとして表示
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path, notice: "スケジュールを作成しました" #成功したら一覧ページへ
    else
      flash.now[:alert] = "スケジュール作成に失敗しました"
      render new_item_path ,status: :unprocessable_entity #失敗したら作成ページへ エラー422ユーザー登録エラーを表示
    end
  end

  def show
    @item = Item.find(params[:id]) #1つのIDのデータを取得
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(params.require(:item).permit(:title,:start,:end,:allday,:memo))
    flash[:notice] = "ID「#{@item.id}」の情報を更新しました"
    redirect_to items_path #一覧ページへ
    else
    render "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:notice] = "ID「#{@item.id}」の情報を削除しました"
    redirect_to items_path #一覧ページへ
  end

  def item_params #フォームで入力した値を渡すメソッド
    params.require(:item).permit(:title,:start,:end,:allday,:memo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h3>ユーザー編集</h3>

<%= form_with model: @item do |f| %> <!--コントローラのnewで設定-->
<%= render 'shared/error_messages' %> <!-- エラーメッセージ -->
<%= render "shared/form", f: f  %> <!--renderの場合には、 f をパーシャルに渡す -->

    <div class="form_footer">
        <ul>
            <li class="to_index_button"><%= link_to "キャンセル", items_path %></li>
            <li><%= f.submit "登録完了する", class: "submit_button"%></li> <!--createアクションで実装-->
        </ul>
    </div>

<% end %>

app/views/items/index.html.erb
<div class="index_title">
<p class="index">予定一覧</p>
<%= link_to "+ 新規追加", new_item_path, class:"index_new" %> <!--button_toの場合にはハッシュ形式でクラス指定-->
</div>

<table class="schedule">
    <thead>
        <tr class="index_table">
            <th>ID</th>
            <th>タイトル</th>
            <th>開始日</th>
            <th>終了日</th>
            <th>終日</th>
            <th>更新日</th>
            <th>詳細</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </thead>

    <tbody>
        <% @items.each do |item| %>
        <tr class="index_table">
            <td><%= item.id %></td>
            <td><%= item.title %></td>
            <td><%= item.start.present? ? I18n.l(item.start, format: :short) : "-" %></td> <!-- ja.yml -->
            <td><%= item.end.present? ? I18n.l(item.end, format: :short) : "-" %></td>
            <td><%= item.allday ? "○" : "" %></td> <!--item.alldayがtrueの時に「○」が表示され、falseの時には空欄が表示-->
            <td><%= item.updated_at? ? I18n.l(item.updated_at, format: :long) : "-" %></td>
            <td class="index_link"><%= link_to "詳細", item_path(item) %></td> <!--詳細ページへ 引数（id)を渡す-->
            <td class="index_link"><%= link_to "編集",  edit_item_path(item) %></td> <!-- 編集ページへ 引数（id)を渡す-->
            <td class="index_link"><%= link_to "削除",  item, method: :delete, data: { confirm: "本当に削除しますか？" } %></td> <!-- item   DELETE /items/:id(.:format)  items#destroy-->

        </tr>
        <% end %>
    </tbody>
</table>

<footer>
<div class="Total">予定合計: <span><%= @items.count %></span> 件</div> <!-- 予定の合計数を表示 -->
<p class="today">本日:<%= l(Date.today, format: :short) %></p><!--日付を表示-->
</footer>

app/views/items/new.html.erb
<h1 class="new_header_text">予定の新規追加</h1>

<%= form_with model: @item do |f| %> <!--コントローラのnewで設定-->
<%= render 'shared/error_messages' %> <!-- エラーメッセージ -->
<%= render "shared/form", f: f  %> <!--renderの場合には、 f をパーシャルに渡す -->

    <div class="form_footer">
        <ul>
            <li class="to_index_button"><%= link_to "キャンセル", items_path %></li>
            <li><%= f.submit "登録完了する", class: "submit_button"%></li> <!--createアクションで実装-->
        </ul>
    </div>
<% end %>

app/views/items/show.html.erb
<div class="index_link">
    <ul>
        <li><%= link_to "← 一覧に戻る", items_path %></li>
    </ul>
</div>

<h3 class="show_header_text"><%= @item.title %></h3>

<p class="show_edit_button"><%= link_to "編集", edit_item_path %></p>

<table class="show_table">
    <tr>
        <th>開始日</th>
        <td><%= @item.start %></td>
    </tr>
    <tr>
        <th>終了日</th>
        <td><%= @item.end %></td>
    </tr>
    <tr>
        <th>終日</th>
        <td><%= @item.allday %></td>
    </tr>
    <tr>
        <th>メモ</th>
        <td><%= @item.memo %></td>
    </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header> 
    <p class="header_text">スケジュール管理アプリ</p>
  </header>

  <body>

    <!-- 成功フラッシュメッセージの表示　-->
    <% if notice %>
        <p class="notice"><%= notice %></p>
    <% end %>

    <%= yield %>

    <div class="debug"><%= debug(params) if Rails.env.development? %></div> <!--開発環境のみでデバッグ情報を表示-->

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if flash[:alert] %>
<div class="error_form">
<% if flash[:alert] %>
    <div class="alert-danger">
        <%= flash[:alert] %>
    </div>
<% end %>

<% if @item.errors.any? %>
    <div id="error_explanation" class="error_explanation_class"> 
        <ul>
            <% @item.errors.full_messages.each do |msg| %> <!-- デフォルト文をja.ymlで一部変換-->
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>
</div>
<% end %>

app/views/shared/_form.html.erb
    <table class="form_table">
        <tr>
            <th><%= f.label :title ,"タイトル" %></th> <!-- 紐付け -->
            <td><%= f.text_field :title, placeholder: "タイトル" %></td> <!-- 一行入力 -->
        </tr>

        <tr class="form_start">
            <th><%= f.label :start ,"開始日" %></th>
            <td><%= f.date_field :start %></td>
        </tr>

        <tr>
            <th><%= f.label :end ,"終了日" %></th>
            <td><%= f.date_field :end %></td>
        </tr>

        <tr>
            <td class="form_allday">
                <%= f.check_box :allday %>
                <%= f.label :allday, "終日の場合はチェックをいれます" %>
            </td>
        </tr>

        <tr>
            <th><%= f.label :memo ,"メモ" %></th>
            <td><%= f.text_area :memo, placeholder: "メモ" %></td> <!-- 複数行入力 placeholderで初期値入力 -->
        </tr>
    </table>